version: "3.9"
services:
  upgraded-parakeet-redis:
    image: redis:latest
    container_name: upgraded-parakeet-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - default

  upgraded-parakeet-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upgraded-parakeet-service
    environment:
      API_BASE_URL: "http://localhost:9292"
      REDIS_HOST: "upgraded-parakeet-redis"
      REDIS_PORT: "6379"
      REDIS_DB: "0"
    ports:
      - "9292:9292"
    depends_on:
      upgraded-parakeet-redis:
        condition: "service_started"
    env_file:
      - ".env"
    volumes:
      - .:/upgraded-parakeet
    networks:
      - default

networks:
  default:
    name: upgraded-parakeet-network
    external: true

volumes:
  redis_data:
    driver: local
